// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/coder-lulu/newbee-core/rpc/ent/api"
	"github.com/coder-lulu/newbee-core/rpc/ent/configuration"
	"github.com/coder-lulu/newbee-core/rpc/ent/department"
	"github.com/coder-lulu/newbee-core/rpc/ent/dictionary"
	"github.com/coder-lulu/newbee-core/rpc/ent/dictionarydetail"
	"github.com/coder-lulu/newbee-core/rpc/ent/menu"
	"github.com/coder-lulu/newbee-core/rpc/ent/oauthprovider"
	"github.com/coder-lulu/newbee-core/rpc/ent/position"
	"github.com/coder-lulu/newbee-core/rpc/ent/role"
	"github.com/coder-lulu/newbee-core/rpc/ent/token"
	"github.com/coder-lulu/newbee-core/rpc/ent/user"
)

// WhereHasTenantWith adds a tenant filter to the query.
func (_m *APIQuery) WhereHasTenantWith(tenantID uint64) {
	_m.predicates = append(_m.predicates, api.TenantIDEQ(tenantID))
}

// WhereHasTenantWith adds a tenant filter to the query.
func (_m *ConfigurationQuery) WhereHasTenantWith(tenantID uint64) {
	_m.predicates = append(_m.predicates, configuration.TenantIDEQ(tenantID))
}

// WhereHasTenantWith adds a tenant filter to the query.
func (_m *DepartmentQuery) WhereHasTenantWith(tenantID uint64) {
	_m.predicates = append(_m.predicates, department.TenantIDEQ(tenantID))
}

// WhereHasTenantWith adds a tenant filter to the query.
func (_m *DictionaryQuery) WhereHasTenantWith(tenantID uint64) {
	_m.predicates = append(_m.predicates, dictionary.TenantIDEQ(tenantID))
}

// WhereHasTenantWith adds a tenant filter to the query.
func (_m *DictionaryDetailQuery) WhereHasTenantWith(tenantID uint64) {
	_m.predicates = append(_m.predicates, dictionarydetail.TenantIDEQ(tenantID))
}

// WhereHasTenantWith adds a tenant filter to the query.
func (_m *MenuQuery) WhereHasTenantWith(tenantID uint64) {
	_m.predicates = append(_m.predicates, menu.TenantIDEQ(tenantID))
}

// WhereHasTenantWith adds a tenant filter to the query.
func (_m *OauthProviderQuery) WhereHasTenantWith(tenantID uint64) {
	_m.predicates = append(_m.predicates, oauthprovider.TenantIDEQ(tenantID))
}

// WhereHasTenantWith adds a tenant filter to the query.
func (_m *PositionQuery) WhereHasTenantWith(tenantID uint64) {
	_m.predicates = append(_m.predicates, position.TenantIDEQ(tenantID))
}

// WhereHasTenantWith adds a tenant filter to the query.
func (_m *RoleQuery) WhereHasTenantWith(tenantID uint64) {
	_m.predicates = append(_m.predicates, role.TenantIDEQ(tenantID))
}

// WhereHasTenantWith adds a tenant filter to the query.
func (_m *TokenQuery) WhereHasTenantWith(tenantID uint64) {
	_m.predicates = append(_m.predicates, token.TenantIDEQ(tenantID))
}

// WhereHasTenantWith adds a tenant filter to the query.
func (_m *UserQuery) WhereHasTenantWith(tenantID uint64) {
	_m.predicates = append(_m.predicates, user.TenantIDEQ(tenantID))
}
