// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/coder-lulu/newbee-core/rpc/ent/predicate"
	"github.com/coder-lulu/newbee-core/rpc/ent/schema/types"
	"github.com/coder-lulu/newbee-core/rpc/ent/tenant"
)

// TenantUpdate is the builder for updating Tenant entities.
type TenantUpdate struct {
	config
	hooks     []Hook
	mutation  *TenantMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the TenantUpdate builder.
func (_u *TenantUpdate) Where(ps ...predicate.Tenant) *TenantUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantUpdate) SetUpdatedAt(v time.Time) *TenantUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *TenantUpdate) SetStatus(v uint8) *TenantUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableStatus(v *uint8) *TenantUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *TenantUpdate) AddStatus(v int8) *TenantUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *TenantUpdate) ClearStatus() *TenantUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *TenantUpdate) SetDeletedAt(v time.Time) *TenantUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableDeletedAt(v *time.Time) *TenantUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *TenantUpdate) ClearDeletedAt() *TenantUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *TenantUpdate) SetName(v string) *TenantUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableName(v *string) *TenantUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *TenantUpdate) SetCode(v string) *TenantUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableCode(v *string) *TenantUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetDomain sets the "domain" field.
func (_u *TenantUpdate) SetDomain(v string) *TenantUpdate {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableDomain(v *string) *TenantUpdate {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// ClearDomain clears the value of the "domain" field.
func (_u *TenantUpdate) ClearDomain() *TenantUpdate {
	_u.mutation.ClearDomain()
	return _u
}

// SetContactPerson sets the "contact_person" field.
func (_u *TenantUpdate) SetContactPerson(v string) *TenantUpdate {
	_u.mutation.SetContactPerson(v)
	return _u
}

// SetNillableContactPerson sets the "contact_person" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableContactPerson(v *string) *TenantUpdate {
	if v != nil {
		_u.SetContactPerson(*v)
	}
	return _u
}

// ClearContactPerson clears the value of the "contact_person" field.
func (_u *TenantUpdate) ClearContactPerson() *TenantUpdate {
	_u.mutation.ClearContactPerson()
	return _u
}

// SetContactPhone sets the "contact_phone" field.
func (_u *TenantUpdate) SetContactPhone(v string) *TenantUpdate {
	_u.mutation.SetContactPhone(v)
	return _u
}

// SetNillableContactPhone sets the "contact_phone" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableContactPhone(v *string) *TenantUpdate {
	if v != nil {
		_u.SetContactPhone(*v)
	}
	return _u
}

// ClearContactPhone clears the value of the "contact_phone" field.
func (_u *TenantUpdate) ClearContactPhone() *TenantUpdate {
	_u.mutation.ClearContactPhone()
	return _u
}

// SetContactEmail sets the "contact_email" field.
func (_u *TenantUpdate) SetContactEmail(v string) *TenantUpdate {
	_u.mutation.SetContactEmail(v)
	return _u
}

// SetNillableContactEmail sets the "contact_email" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableContactEmail(v *string) *TenantUpdate {
	if v != nil {
		_u.SetContactEmail(*v)
	}
	return _u
}

// ClearContactEmail clears the value of the "contact_email" field.
func (_u *TenantUpdate) ClearContactEmail() *TenantUpdate {
	_u.mutation.ClearContactEmail()
	return _u
}

// SetDescription sets the "description" field.
func (_u *TenantUpdate) SetDescription(v string) *TenantUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableDescription(v *string) *TenantUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TenantUpdate) ClearDescription() *TenantUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetExpireTime sets the "expire_time" field.
func (_u *TenantUpdate) SetExpireTime(v time.Time) *TenantUpdate {
	_u.mutation.SetExpireTime(v)
	return _u
}

// SetNillableExpireTime sets the "expire_time" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableExpireTime(v *time.Time) *TenantUpdate {
	if v != nil {
		_u.SetExpireTime(*v)
	}
	return _u
}

// ClearExpireTime clears the value of the "expire_time" field.
func (_u *TenantUpdate) ClearExpireTime() *TenantUpdate {
	_u.mutation.ClearExpireTime()
	return _u
}

// SetMaxUsers sets the "max_users" field.
func (_u *TenantUpdate) SetMaxUsers(v uint32) *TenantUpdate {
	_u.mutation.ResetMaxUsers()
	_u.mutation.SetMaxUsers(v)
	return _u
}

// SetNillableMaxUsers sets the "max_users" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableMaxUsers(v *uint32) *TenantUpdate {
	if v != nil {
		_u.SetMaxUsers(*v)
	}
	return _u
}

// AddMaxUsers adds value to the "max_users" field.
func (_u *TenantUpdate) AddMaxUsers(v int32) *TenantUpdate {
	_u.mutation.AddMaxUsers(v)
	return _u
}

// SetSettings sets the "settings" field.
func (_u *TenantUpdate) SetSettings(v []types.TenantSettings) *TenantUpdate {
	_u.mutation.SetSettings(v)
	return _u
}

// AppendSettings appends value to the "settings" field.
func (_u *TenantUpdate) AppendSettings(v []types.TenantSettings) *TenantUpdate {
	_u.mutation.AppendSettings(v)
	return _u
}

// ClearSettings clears the value of the "settings" field.
func (_u *TenantUpdate) ClearSettings() *TenantUpdate {
	_u.mutation.ClearSettings()
	return _u
}

// Mutation returns the TenantMutation object of the builder.
func (_u *TenantUpdate) Mutation() *TenantMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TenantUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TenantUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if tenant.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized tenant.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := tenant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TenantUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TenantUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TenantUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(tenant.Table, tenant.Columns, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenant.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tenant.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(tenant.FieldStatus, field.TypeUint8, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(tenant.FieldStatus, field.TypeUint8)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(tenant.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(tenant.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tenant.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(tenant.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(tenant.FieldDomain, field.TypeString, value)
	}
	if _u.mutation.DomainCleared() {
		_spec.ClearField(tenant.FieldDomain, field.TypeString)
	}
	if value, ok := _u.mutation.ContactPerson(); ok {
		_spec.SetField(tenant.FieldContactPerson, field.TypeString, value)
	}
	if _u.mutation.ContactPersonCleared() {
		_spec.ClearField(tenant.FieldContactPerson, field.TypeString)
	}
	if value, ok := _u.mutation.ContactPhone(); ok {
		_spec.SetField(tenant.FieldContactPhone, field.TypeString, value)
	}
	if _u.mutation.ContactPhoneCleared() {
		_spec.ClearField(tenant.FieldContactPhone, field.TypeString)
	}
	if value, ok := _u.mutation.ContactEmail(); ok {
		_spec.SetField(tenant.FieldContactEmail, field.TypeString, value)
	}
	if _u.mutation.ContactEmailCleared() {
		_spec.ClearField(tenant.FieldContactEmail, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(tenant.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(tenant.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.ExpireTime(); ok {
		_spec.SetField(tenant.FieldExpireTime, field.TypeTime, value)
	}
	if _u.mutation.ExpireTimeCleared() {
		_spec.ClearField(tenant.FieldExpireTime, field.TypeTime)
	}
	if value, ok := _u.mutation.MaxUsers(); ok {
		_spec.SetField(tenant.FieldMaxUsers, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedMaxUsers(); ok {
		_spec.AddField(tenant.FieldMaxUsers, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.Settings(); ok {
		_spec.SetField(tenant.FieldSettings, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSettings(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tenant.FieldSettings, value)
		})
	}
	if _u.mutation.SettingsCleared() {
		_spec.ClearField(tenant.FieldSettings, field.TypeJSON)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TenantUpdateOne is the builder for updating a single Tenant entity.
type TenantUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *TenantMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantUpdateOne) SetUpdatedAt(v time.Time) *TenantUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *TenantUpdateOne) SetStatus(v uint8) *TenantUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableStatus(v *uint8) *TenantUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *TenantUpdateOne) AddStatus(v int8) *TenantUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *TenantUpdateOne) ClearStatus() *TenantUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *TenantUpdateOne) SetDeletedAt(v time.Time) *TenantUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableDeletedAt(v *time.Time) *TenantUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *TenantUpdateOne) ClearDeletedAt() *TenantUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *TenantUpdateOne) SetName(v string) *TenantUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableName(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *TenantUpdateOne) SetCode(v string) *TenantUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableCode(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetDomain sets the "domain" field.
func (_u *TenantUpdateOne) SetDomain(v string) *TenantUpdateOne {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableDomain(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// ClearDomain clears the value of the "domain" field.
func (_u *TenantUpdateOne) ClearDomain() *TenantUpdateOne {
	_u.mutation.ClearDomain()
	return _u
}

// SetContactPerson sets the "contact_person" field.
func (_u *TenantUpdateOne) SetContactPerson(v string) *TenantUpdateOne {
	_u.mutation.SetContactPerson(v)
	return _u
}

// SetNillableContactPerson sets the "contact_person" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableContactPerson(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetContactPerson(*v)
	}
	return _u
}

// ClearContactPerson clears the value of the "contact_person" field.
func (_u *TenantUpdateOne) ClearContactPerson() *TenantUpdateOne {
	_u.mutation.ClearContactPerson()
	return _u
}

// SetContactPhone sets the "contact_phone" field.
func (_u *TenantUpdateOne) SetContactPhone(v string) *TenantUpdateOne {
	_u.mutation.SetContactPhone(v)
	return _u
}

// SetNillableContactPhone sets the "contact_phone" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableContactPhone(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetContactPhone(*v)
	}
	return _u
}

// ClearContactPhone clears the value of the "contact_phone" field.
func (_u *TenantUpdateOne) ClearContactPhone() *TenantUpdateOne {
	_u.mutation.ClearContactPhone()
	return _u
}

// SetContactEmail sets the "contact_email" field.
func (_u *TenantUpdateOne) SetContactEmail(v string) *TenantUpdateOne {
	_u.mutation.SetContactEmail(v)
	return _u
}

// SetNillableContactEmail sets the "contact_email" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableContactEmail(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetContactEmail(*v)
	}
	return _u
}

// ClearContactEmail clears the value of the "contact_email" field.
func (_u *TenantUpdateOne) ClearContactEmail() *TenantUpdateOne {
	_u.mutation.ClearContactEmail()
	return _u
}

// SetDescription sets the "description" field.
func (_u *TenantUpdateOne) SetDescription(v string) *TenantUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableDescription(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TenantUpdateOne) ClearDescription() *TenantUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetExpireTime sets the "expire_time" field.
func (_u *TenantUpdateOne) SetExpireTime(v time.Time) *TenantUpdateOne {
	_u.mutation.SetExpireTime(v)
	return _u
}

// SetNillableExpireTime sets the "expire_time" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableExpireTime(v *time.Time) *TenantUpdateOne {
	if v != nil {
		_u.SetExpireTime(*v)
	}
	return _u
}

// ClearExpireTime clears the value of the "expire_time" field.
func (_u *TenantUpdateOne) ClearExpireTime() *TenantUpdateOne {
	_u.mutation.ClearExpireTime()
	return _u
}

// SetMaxUsers sets the "max_users" field.
func (_u *TenantUpdateOne) SetMaxUsers(v uint32) *TenantUpdateOne {
	_u.mutation.ResetMaxUsers()
	_u.mutation.SetMaxUsers(v)
	return _u
}

// SetNillableMaxUsers sets the "max_users" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableMaxUsers(v *uint32) *TenantUpdateOne {
	if v != nil {
		_u.SetMaxUsers(*v)
	}
	return _u
}

// AddMaxUsers adds value to the "max_users" field.
func (_u *TenantUpdateOne) AddMaxUsers(v int32) *TenantUpdateOne {
	_u.mutation.AddMaxUsers(v)
	return _u
}

// SetSettings sets the "settings" field.
func (_u *TenantUpdateOne) SetSettings(v []types.TenantSettings) *TenantUpdateOne {
	_u.mutation.SetSettings(v)
	return _u
}

// AppendSettings appends value to the "settings" field.
func (_u *TenantUpdateOne) AppendSettings(v []types.TenantSettings) *TenantUpdateOne {
	_u.mutation.AppendSettings(v)
	return _u
}

// ClearSettings clears the value of the "settings" field.
func (_u *TenantUpdateOne) ClearSettings() *TenantUpdateOne {
	_u.mutation.ClearSettings()
	return _u
}

// Mutation returns the TenantMutation object of the builder.
func (_u *TenantUpdateOne) Mutation() *TenantMutation {
	return _u.mutation
}

// Where appends a list predicates to the TenantUpdate builder.
func (_u *TenantUpdateOne) Where(ps ...predicate.Tenant) *TenantUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TenantUpdateOne) Select(field string, fields ...string) *TenantUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Tenant entity.
func (_u *TenantUpdateOne) Save(ctx context.Context) (*Tenant, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantUpdateOne) SaveX(ctx context.Context) *Tenant {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TenantUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if tenant.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized tenant.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := tenant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TenantUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TenantUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TenantUpdateOne) sqlSave(ctx context.Context) (_node *Tenant, err error) {
	_spec := sqlgraph.NewUpdateSpec(tenant.Table, tenant.Columns, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Tenant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenant.FieldID)
		for _, f := range fields {
			if !tenant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tenant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenant.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tenant.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(tenant.FieldStatus, field.TypeUint8, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(tenant.FieldStatus, field.TypeUint8)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(tenant.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(tenant.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tenant.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(tenant.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(tenant.FieldDomain, field.TypeString, value)
	}
	if _u.mutation.DomainCleared() {
		_spec.ClearField(tenant.FieldDomain, field.TypeString)
	}
	if value, ok := _u.mutation.ContactPerson(); ok {
		_spec.SetField(tenant.FieldContactPerson, field.TypeString, value)
	}
	if _u.mutation.ContactPersonCleared() {
		_spec.ClearField(tenant.FieldContactPerson, field.TypeString)
	}
	if value, ok := _u.mutation.ContactPhone(); ok {
		_spec.SetField(tenant.FieldContactPhone, field.TypeString, value)
	}
	if _u.mutation.ContactPhoneCleared() {
		_spec.ClearField(tenant.FieldContactPhone, field.TypeString)
	}
	if value, ok := _u.mutation.ContactEmail(); ok {
		_spec.SetField(tenant.FieldContactEmail, field.TypeString, value)
	}
	if _u.mutation.ContactEmailCleared() {
		_spec.ClearField(tenant.FieldContactEmail, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(tenant.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(tenant.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.ExpireTime(); ok {
		_spec.SetField(tenant.FieldExpireTime, field.TypeTime, value)
	}
	if _u.mutation.ExpireTimeCleared() {
		_spec.ClearField(tenant.FieldExpireTime, field.TypeTime)
	}
	if value, ok := _u.mutation.MaxUsers(); ok {
		_spec.SetField(tenant.FieldMaxUsers, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedMaxUsers(); ok {
		_spec.AddField(tenant.FieldMaxUsers, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.Settings(); ok {
		_spec.SetField(tenant.FieldSettings, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSettings(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tenant.FieldSettings, value)
		})
	}
	if _u.mutation.SettingsCleared() {
		_spec.ClearField(tenant.FieldSettings, field.TypeJSON)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Tenant{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
