// Code generated by ent, DO NOT EDIT.

package dictionarydetail

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/coder-lulu/newbee-core/rpc/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldUpdatedAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v uint8) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldStatus, v))
}

// Sort applies equality check predicate on the "sort" field. It's identical to SortEQ.
func Sort(v uint32) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldSort, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint64) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldTenantID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldTitle, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldValue, v))
}

// ListClass applies equality check predicate on the "list_class" field. It's identical to ListClassEQ.
func ListClass(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldListClass, v))
}

// CSSClass applies equality check predicate on the "css_class" field. It's identical to CSSClassEQ.
func CSSClass(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldCSSClass, v))
}

// IsDefault applies equality check predicate on the "is_default" field. It's identical to IsDefaultEQ.
func IsDefault(v uint32) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldIsDefault, v))
}

// DictionaryID applies equality check predicate on the "dictionary_id" field. It's identical to DictionaryIDEQ.
func DictionaryID(v uint64) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldDictionaryID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLTE(FieldUpdatedAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v uint8) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v uint8) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...uint8) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...uint8) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v uint8) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v uint8) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v uint8) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v uint8) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLTE(FieldStatus, v))
}

// StatusIsNil applies the IsNil predicate on the "status" field.
func StatusIsNil() predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIsNull(FieldStatus))
}

// StatusNotNil applies the NotNil predicate on the "status" field.
func StatusNotNil() predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotNull(FieldStatus))
}

// SortEQ applies the EQ predicate on the "sort" field.
func SortEQ(v uint32) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldSort, v))
}

// SortNEQ applies the NEQ predicate on the "sort" field.
func SortNEQ(v uint32) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNEQ(FieldSort, v))
}

// SortIn applies the In predicate on the "sort" field.
func SortIn(vs ...uint32) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIn(FieldSort, vs...))
}

// SortNotIn applies the NotIn predicate on the "sort" field.
func SortNotIn(vs ...uint32) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotIn(FieldSort, vs...))
}

// SortGT applies the GT predicate on the "sort" field.
func SortGT(v uint32) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGT(FieldSort, v))
}

// SortGTE applies the GTE predicate on the "sort" field.
func SortGTE(v uint32) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGTE(FieldSort, v))
}

// SortLT applies the LT predicate on the "sort" field.
func SortLT(v uint32) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLT(FieldSort, v))
}

// SortLTE applies the LTE predicate on the "sort" field.
func SortLTE(v uint32) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLTE(FieldSort, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint64) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint64) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint64) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint64) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint64) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint64) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint64) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint64) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLTE(FieldTenantID, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldContainsFold(FieldTitle, v))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLTE(FieldValue, v))
}

// ValueContains applies the Contains predicate on the "value" field.
func ValueContains(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldContains(FieldValue, v))
}

// ValueHasPrefix applies the HasPrefix predicate on the "value" field.
func ValueHasPrefix(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldHasPrefix(FieldValue, v))
}

// ValueHasSuffix applies the HasSuffix predicate on the "value" field.
func ValueHasSuffix(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldHasSuffix(FieldValue, v))
}

// ValueEqualFold applies the EqualFold predicate on the "value" field.
func ValueEqualFold(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEqualFold(FieldValue, v))
}

// ValueContainsFold applies the ContainsFold predicate on the "value" field.
func ValueContainsFold(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldContainsFold(FieldValue, v))
}

// ListClassEQ applies the EQ predicate on the "list_class" field.
func ListClassEQ(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldListClass, v))
}

// ListClassNEQ applies the NEQ predicate on the "list_class" field.
func ListClassNEQ(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNEQ(FieldListClass, v))
}

// ListClassIn applies the In predicate on the "list_class" field.
func ListClassIn(vs ...string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIn(FieldListClass, vs...))
}

// ListClassNotIn applies the NotIn predicate on the "list_class" field.
func ListClassNotIn(vs ...string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotIn(FieldListClass, vs...))
}

// ListClassGT applies the GT predicate on the "list_class" field.
func ListClassGT(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGT(FieldListClass, v))
}

// ListClassGTE applies the GTE predicate on the "list_class" field.
func ListClassGTE(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGTE(FieldListClass, v))
}

// ListClassLT applies the LT predicate on the "list_class" field.
func ListClassLT(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLT(FieldListClass, v))
}

// ListClassLTE applies the LTE predicate on the "list_class" field.
func ListClassLTE(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLTE(FieldListClass, v))
}

// ListClassContains applies the Contains predicate on the "list_class" field.
func ListClassContains(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldContains(FieldListClass, v))
}

// ListClassHasPrefix applies the HasPrefix predicate on the "list_class" field.
func ListClassHasPrefix(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldHasPrefix(FieldListClass, v))
}

// ListClassHasSuffix applies the HasSuffix predicate on the "list_class" field.
func ListClassHasSuffix(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldHasSuffix(FieldListClass, v))
}

// ListClassIsNil applies the IsNil predicate on the "list_class" field.
func ListClassIsNil() predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIsNull(FieldListClass))
}

// ListClassNotNil applies the NotNil predicate on the "list_class" field.
func ListClassNotNil() predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotNull(FieldListClass))
}

// ListClassEqualFold applies the EqualFold predicate on the "list_class" field.
func ListClassEqualFold(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEqualFold(FieldListClass, v))
}

// ListClassContainsFold applies the ContainsFold predicate on the "list_class" field.
func ListClassContainsFold(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldContainsFold(FieldListClass, v))
}

// CSSClassEQ applies the EQ predicate on the "css_class" field.
func CSSClassEQ(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldCSSClass, v))
}

// CSSClassNEQ applies the NEQ predicate on the "css_class" field.
func CSSClassNEQ(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNEQ(FieldCSSClass, v))
}

// CSSClassIn applies the In predicate on the "css_class" field.
func CSSClassIn(vs ...string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIn(FieldCSSClass, vs...))
}

// CSSClassNotIn applies the NotIn predicate on the "css_class" field.
func CSSClassNotIn(vs ...string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotIn(FieldCSSClass, vs...))
}

// CSSClassGT applies the GT predicate on the "css_class" field.
func CSSClassGT(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGT(FieldCSSClass, v))
}

// CSSClassGTE applies the GTE predicate on the "css_class" field.
func CSSClassGTE(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGTE(FieldCSSClass, v))
}

// CSSClassLT applies the LT predicate on the "css_class" field.
func CSSClassLT(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLT(FieldCSSClass, v))
}

// CSSClassLTE applies the LTE predicate on the "css_class" field.
func CSSClassLTE(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLTE(FieldCSSClass, v))
}

// CSSClassContains applies the Contains predicate on the "css_class" field.
func CSSClassContains(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldContains(FieldCSSClass, v))
}

// CSSClassHasPrefix applies the HasPrefix predicate on the "css_class" field.
func CSSClassHasPrefix(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldHasPrefix(FieldCSSClass, v))
}

// CSSClassHasSuffix applies the HasSuffix predicate on the "css_class" field.
func CSSClassHasSuffix(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldHasSuffix(FieldCSSClass, v))
}

// CSSClassIsNil applies the IsNil predicate on the "css_class" field.
func CSSClassIsNil() predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIsNull(FieldCSSClass))
}

// CSSClassNotNil applies the NotNil predicate on the "css_class" field.
func CSSClassNotNil() predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotNull(FieldCSSClass))
}

// CSSClassEqualFold applies the EqualFold predicate on the "css_class" field.
func CSSClassEqualFold(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEqualFold(FieldCSSClass, v))
}

// CSSClassContainsFold applies the ContainsFold predicate on the "css_class" field.
func CSSClassContainsFold(v string) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldContainsFold(FieldCSSClass, v))
}

// IsDefaultEQ applies the EQ predicate on the "is_default" field.
func IsDefaultEQ(v uint32) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldIsDefault, v))
}

// IsDefaultNEQ applies the NEQ predicate on the "is_default" field.
func IsDefaultNEQ(v uint32) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNEQ(FieldIsDefault, v))
}

// IsDefaultIn applies the In predicate on the "is_default" field.
func IsDefaultIn(vs ...uint32) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIn(FieldIsDefault, vs...))
}

// IsDefaultNotIn applies the NotIn predicate on the "is_default" field.
func IsDefaultNotIn(vs ...uint32) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotIn(FieldIsDefault, vs...))
}

// IsDefaultGT applies the GT predicate on the "is_default" field.
func IsDefaultGT(v uint32) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGT(FieldIsDefault, v))
}

// IsDefaultGTE applies the GTE predicate on the "is_default" field.
func IsDefaultGTE(v uint32) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldGTE(FieldIsDefault, v))
}

// IsDefaultLT applies the LT predicate on the "is_default" field.
func IsDefaultLT(v uint32) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLT(FieldIsDefault, v))
}

// IsDefaultLTE applies the LTE predicate on the "is_default" field.
func IsDefaultLTE(v uint32) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldLTE(FieldIsDefault, v))
}

// IsDefaultIsNil applies the IsNil predicate on the "is_default" field.
func IsDefaultIsNil() predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIsNull(FieldIsDefault))
}

// IsDefaultNotNil applies the NotNil predicate on the "is_default" field.
func IsDefaultNotNil() predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotNull(FieldIsDefault))
}

// DictionaryIDEQ applies the EQ predicate on the "dictionary_id" field.
func DictionaryIDEQ(v uint64) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldEQ(FieldDictionaryID, v))
}

// DictionaryIDNEQ applies the NEQ predicate on the "dictionary_id" field.
func DictionaryIDNEQ(v uint64) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNEQ(FieldDictionaryID, v))
}

// DictionaryIDIn applies the In predicate on the "dictionary_id" field.
func DictionaryIDIn(vs ...uint64) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIn(FieldDictionaryID, vs...))
}

// DictionaryIDNotIn applies the NotIn predicate on the "dictionary_id" field.
func DictionaryIDNotIn(vs ...uint64) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotIn(FieldDictionaryID, vs...))
}

// DictionaryIDIsNil applies the IsNil predicate on the "dictionary_id" field.
func DictionaryIDIsNil() predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldIsNull(FieldDictionaryID))
}

// DictionaryIDNotNil applies the NotNil predicate on the "dictionary_id" field.
func DictionaryIDNotNil() predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.FieldNotNull(FieldDictionaryID))
}

// HasDictionaries applies the HasEdge predicate on the "dictionaries" edge.
func HasDictionaries() predicate.DictionaryDetail {
	return predicate.DictionaryDetail(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DictionariesTable, DictionariesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDictionariesWith applies the HasEdge predicate on the "dictionaries" edge with a given conditions (other predicates).
func HasDictionariesWith(preds ...predicate.Dictionary) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(func(s *sql.Selector) {
		step := newDictionariesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DictionaryDetail) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DictionaryDetail) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DictionaryDetail) predicate.DictionaryDetail {
	return predicate.DictionaryDetail(sql.NotPredicates(p))
}
